openapi: 3.0.0
info:
    version: '1.0'
    title: 'LBAW StackUnderFlow Web API'
    description: 'Web resources specification (A7) for StackUnderFlow'

servers:
    - url: 
      description: Production server

externalDocs: 
    description: Find more info here.
    url: 

tags: 
    - name: 'M01: Authentication and  Individual Profile'
    - name: 'M02: Questions'
    - name: 'M03: Answers'
    - name: 'M04: Comments'
    - name: 'M05: User Administration and Static pages'
    - name: 'M06: Searches'

paths:
    #------------------M01-------------------
    #login
    /login:
        get:
          operationId: R101
          summary: 'R101: Login Form'
          description: 'Provide the form for the user login.'
          tags:
            - 'M01: Authentication and  Individual Profile'
          responses:
              '200':
                  description: 'Went well. Show the form UI.'

        post:
            operationId: R102
            summary: 'R102: Login Action'
            description: 'Login to the website.'
            tags:
              - 'M01: Authentication and  Individual Profile'

            requestBody:
                required: True
                content:
                    application/x-www-form-urlencoded:
                        schema:
                            type: object
                            properties:
                                password:
                                    type: string
                                email:
                                    type: string
                            required:
                                - inputPassword
                                - inputEmail
            responses:
                '302':
                    description: 'Redirect after login'
                    headers:
                      Location:
                        schema:
                          type: string
                        examples:
                          302Success:
                            description: 'Ok. Redirect to Home Page'
                            value: '/'
                          302Error:
                            description: 'Failed Authentication. Redirect to login form.'
                            value: '/login'
    /logout:
      post:
        operationId: R102
        summary: 'R102: Logout Action'
        description: 'Logout the current authenticated user.'
        tags:
          - 'M01: Authentication and  Individual Profile'
        responses:
          '302':
            description: 'Redirect after processing logout.'
            headers:
              Location:
                schema:
                  type: string
                examples:
                  302Success:
                    description: 'Successful logout. Redirect to homepage.'
                    value: '/'
    /register:
      get:
        operationId: R104
        summary: 'R104: Signup Form'
        description: 'Provide Signup form.'
        tags:
          - 'M01: Authentication and  Individual Profile'
        responses:
          '200':
            description: 'Went well. Show signup form.'
      post:
        operationId: R105
        summary: 'R105: Signup Action'
        description: 'Signup to the website'
        tags:
          - 'M01: Authentication and  Individual Profile'
        requestBody:
          required: True
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  password:
                    type: string
                  email:
                    type: string
                required:
                  - name
                  - password
                  - email
        responses:
          '302':
            description: 'Redirect after processing signup credentials.'
            headers:
              Location:
                schema:
                  type: string
                examples:
                  302Success:
                    description: 'Successful credential insertion. Redirect to home page.'
                    value: '/'
                  302Error:
                    description: 'Failed credential insertion. Redirect to signup form'
                    value: '/register'

    /user/{id}/profile:
      get:
        operationId: R106
        summary: 'R106: View user Profile'
        description: 'Show the individual user profile'
        tags:
          - 'M01: Authentication and  Individual Profile'
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: True
        responses:
          '200':
            description: 'Ok. Show user profile'
      post:
        operationId: R107
        summary: 'R107: Edit Profile'
        description: 'Process the new user edition form submission.'
        tags: 
          - 'M01: Authentication and  Individual Profile'
        parameters:
          - in: path
            name: id
            schema:
              type: integer
              required: True
        requestBody:
          required: True
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  picture:
                    type: string
                  email:
                    type: string
        responses:
          '302':
            description: 'Redirect after processing the user new information.'
            headers:
              Location:
                schema:
                  type: string
                examples:
                  302Success:
                    description: 'Successful profile edition. Redirect to user profile.'
                    value: '/users/{id}/profile'
                  302Failure:
                    description: 'Failed to edit. Redirect to user profile.'
                    value: '/users/{id}/profile'
      /users/{id}/profile/edit:
        get: 
            operationId: R107
            summary: 'R107: View user profile edit form'
            description: 'Show the individual user profile edition form. Access: USR'
            tags:
                - 'M01: Authentication and Profile'

            parameters:
              - in: path
                name: id
                schema:
                    type: integer
                required: true

            responses:
                '200':
                  description: 'Ok. Show profile edition form UI.'

#------------------ M02 --------------------

    /question/create:
      get:
        operationId: R201
        summary: 'R201: Get the question creation form.'
        description: 'Show the question creation form to the User'
        tags:
          - 'M02: Questions'
        responses:
          '200':  
            description: 'Ok. Show Create Question Form UI.'
    /question:
      post:
        operationId: R202
        summary: 'R202: Create Questions'
        description: 'Process the Create Question Form submission.'
        tags:
          - 'M02: Questions'
        requestBody:
          required: true
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                    title:
                      type: string
                    content:
                      type: string
        responses:
          '302':
            description: 'Redirect after the question has been created'
            headers:
              Location:
                schema:
                  type: string
                examples:
                  302Success:
                    description: 'Successful question creation'
                    value: '/home'
                  302Failure:
                    description: 'Failed to create the question. Redirect to homepage.'
                    value: '/home'

    /question/{question}/show:
      get:
        operationId: R203
        summary: 'R203: Get the question to show'
        description: 'Show the individual page for a question with it''s information'
        tags:
          # - 'M02: Questions'
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: True
        responses:
          '200':
            description: 'Ok. Show Question Page'

    /question/{question}/edit:
      get:
        operationId: R204
        summary: 'R204: Get the form to edit a Question'
        description: 'Turn the question field into editable areas'
        tags:
          - 'M02: Questions'
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: True
        responses:
          '200':
            description: 'Ok. Change the fields into editable'
      put:
        operationId: R205
        summary: 'R205: Edit the question'
        description: 'Process the new information and update the question'
        tags:
          - 'M02: Questions'
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: True
        requestBody:
          required: True
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  content:
                    type: string
                required:
                  - title
                  - content
        responses:
          '302':
            description: 'Redirect after updating question information'
            headers:
              Location:
                schema:
                  type: string
                examples: 
                  302Success:
                    description: 'Successfully Updated the question. Redirect to home Page'
                    value: '/home'
                  302Failure:
                    description: 'Failed to edit and update the question'
                    value: '/home'
    /question/{question}/delete:
      delete:
        operationId: R206
        summary: 'R206: Delete a question'
        description: 'Process the deletion of a question.'
        tags:
         - 'M02: Questions'
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: True
        responses:
          '302':
            description: 'Redirect user after deleting a question'
            headers:
              Location:
                schema:
                  type: string
                examples:
                  302Success:
                    description: 'Successfully deleted. Redirect to homepage.'
                    value: '/home'
                  302Failure:
                    description: 'Failed to delete the question. Redirect to homepage'
                    value: '/home'
    /top_questions:
      get:
        operationId: R207
        summary: 'R207: View Top Questions'
        description: 'Show the top questions in the database'
        tags:
         - 'M02: Questions'
        responses:
          '200':
            description: 'Ok. Show top Questions'
    
#-------------- M03 -----------------------------------------

    /question/{question}/answer:
      post:
        operationId: R301
        summary: 'R301: Create an answer'
        description: 'Process the answer form and create the answer'
        tags:
          - 'M03: Answers'
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: True

        requestBody:
          required: True
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  content:
                    type: string
                required:
                  - content
        responses:
          '302':
            description: 'Redirect after creating the new Answer'
            headers:
              Location:
                schema: 
                  type: string
                examples:
                  302Success:
                    description: 'Successfully created an answer. Redirect to Question Page'
                    value: '/question/{question}/show'
                  302Failure:
                    description: 'Failed to create an answer. Redirect to the question page'
                    value: '/question/{question}/show'
    /answer/{answer}/show:
      get:
        operationId: R302
        summary: 'R302: Show the answer'
        description: 'Show the question page relative to that answer, with that answer'
        tags:
        - 'M03: Answers'

        responses:
          '200': 
            description: 'Ok. Show the question relative to answer with it''s answrs included'

    /answer/{answer}/edit:
      get:
        operationId: R303
        summary: 'R303: Get the form to edit a Answer'
        description: 'Turn the answer field into editable areas'
        tags:
          - 'M03: Answers'
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: True
        responses:
          '200':
            description: 'Ok. Change the fields into editable'
      put:
        operationId: R304
        summary: 'R304: Edit the answer'
        description: 'Process the new information and update the answer'
        tags:
          - 'M03: Answers'
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: True
        requestBody:
          required: True
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  content:
                    type: string
                required:
                  - title
                  - content
        responses:
          '302':
            description: 'Redirect after updating answer information'
            headers:
              Location:
                schema:
                  type: string
                examples: 
                  302Success:
                    description: 'Successfully Updated the answer. Redirect to question page'
                    value: '/question/{question}/show'
                  302Failure:
                    description: 'Failed to edit and update the answer'
                    value: '/question/{question}/show'

    /answer/{answer}/delete:
      delete:
        operationId: R304
        summary: 'R304: Delete an answer'
        description: 'Process the deletion of an answer.'
        tags:
         - 'M03: Answers'
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: True
        responses:
          '302':
            description: 'Redirect user after deleting an answer'
            headers:
              Location:
                schema:
                  type: string
                examples:
                  302Success:
                    description: 'Successfully deleted. Redirect to question page.'
                    value: '/question/{question}/show'
                  302Failure:
                    description: 'Failed to delete the answer. Redirect to question page'
                    value: '/question/{question}/show'

#-------------------- M04 -----------------------
    /comment/create:
      post:
        operationId: R401
        summary: 'R401: Create comment'
        description: 'Process the comment form and create the comment'
        tags:
          - 'M04: Comments'


        requestBody:
          required: True
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  content:
                    type: string
                required:
                  - content
        responses:
          '302':
            description: 'Redirect after creating the new Comment'
            headers:
              Location:
                schema: 
                  type: string
                examples:
                  302Success:
                    description: 'Successfully created a comment. Redirect to question page'
                    value: '/question/{question}/show'
                  302Failure:
                    description: 'Failed to create a comment. Redirect to the question page'
                    value: '/question/{question}/show'


    /comment/{id}/show:
      get:
        operationId: R402
        summary: 'R402: Show comment'
        description: 'Show the question page relative to the question/answer that owns the comment'
        tags:
        - 'M04: Comments'

        responses:
          '200': 
            description: 'Ok. Show the question relative to the question/answer that owns the comment'

    /comment/{id}/delete:
      delete:
        operationId: R403
        summary: 'R403: Delete comment'
        description: 'Process the deletion of a comment.'
        tags:
         - 'M04: Comments'
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: True
        responses:
          '302':
            description: 'Redirect user after deleting a comment'
            headers:
              Location:
                schema:
                  type: string
                examples:
                  302Success:
                    description: 'Successfully deleted. Redirect to question page.'
                    value: '/question/{question}/show'
                  302Failure:
                    description: 'Failed to delete the answer. Redirect to question page'
                    value: '/question/{question}/show'

#--------------- M05 --------------------

    /home:
      get:
        operationId: R501
        summary: 'R501: Show the Home page'
        description: 'Show the view for the home page'
        tags:
          - 'M05: User Administration and Static pages'
        responses:
          '200':
            description: 'Ok. Show Home Page'


#--------------- M06 --------------------

    /search:
      get:
        operationId: R601
        summary: 'R601: Show search results'
        description: 'Show the result of the Searche'
        tags:
          - 'M06: Searches'
        responses:
          '200':
            description: 'Ok. Show search results'



    


      



           


                  


